name: Upload Release Artifacts

on:
  push:
    tags: [ '*' ]

env:
  JAVA_VERSION: 21
  TAG: ${{ github.ref_name }}
  BUILD_NUMBER: ${{ github.run_number }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      attestations: write
      contents: read
    steps:
      # Setup
      - uses: actions/checkout@v4
      - name: Set up JDK ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: 'microsoft'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          cache-encryption-key: ${{ secrets.GRADLE_CONFIG_CACHE_ENCRYPTION_KEY }}
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
      - name: Get current time
        uses: srfrnk/current-time@master
        id: current-time
        with:
          format: YYYYMMDDHHmmss

      # Build
      - name: Build with Gradle
        env:
          BUILD_TIME: ${{ steps.current-time.outputs.formattedTime }}
        run: ./gradlew :Common:assemble :Fabric:assemble --rerun-tasks

      # Upload
      - name: Upload build artifacts (Common)
        continue-on-error: true
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.repository.name }}-Common-${{ env.TAG }}
          path: |
            Common/build/libs/*.jar
            !Common/build/libs/*-renderdoc-loader.jar
      - name: Upload build artifacts (Fabric)
        continue-on-error: true
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.repository.name }}-Fabric-${{ env.TAG }}
          path: |
            Fabric/build/libs/*.jar
      - name: Generate build attestation
        uses: actions/attest-build-provenance@v2
        with:
          subject-path: |
            **/build/libs/*.jar
            !**/build/libs/*-sources.jar
            !**/build/libs/*-javadoc.jar
            !**/build/libs/*-renderdoc-loader.jar

  publish_github:
    name: Publish (GitHub Releases)
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download build artifacts (Common)
        uses: actions/download-artifact@v4
        with:
          name: ${{ github.event.repository.name }}-Common-${{ env.TAG }}
          path: Common/build/libs
      - name: Download build artifacts (Fabric)
        uses: actions/download-artifact@v4
        with:
          name: ${{ github.event.repository.name }}-Fabric-${{ env.TAG }}
          path: Fabric/build/libs
      - name: Publish (GitHub Releases)
        id: publish_github
        uses: Kira-NT/mc-publish@995edadc13559a8b28d0b7e6571229f067ec7659
        with:
          github-token: ${{ github.token }}
          version-type: beta
          files: |
            **/build/libs/*.jar

  notify:
    name: Notify
    needs: [ publish_github ]
    runs-on: ubuntu-latest
    steps:
      - name: Notify Discord
        uses: Up-Mods/action-discord-release@main
        with:
          version: ${{ env.TAG }}
          webhook-url: ${{ secrets.ANNOUNCEMENT_WEBHOOK_URL }}
          ping-notification-role: false
